/* ============================================================================
   God's Eyes · Financial Model — B2C Homecare (Children)
   The full calculation engine + rendering + interaction lives in this one file.
   Every input on the page is freely editable — no input is locked or
   auto-derived from another input. "Base volume" is just a plain number
   field, with a note explaining where the number came from (see the note
   box in the HTML).
   ============================================================================ */

/* ---------------------------------------------------------------------------
   0. ADMIN CONFIG — for the "Save as Default" tool in the Admin section.
   The PIN is a soft deterrent only (this is a static site — anyone can read
   this file), NOT real security. Change it before you deploy if you want a
   different one. It does not gate anything except showing the Admin form.
   --------------------------------------------------------------------------- */
const ADMIN_CONFIG = {
  pin: "2468"
};

/* ---------------------------------------------------------------------------
   1. DEFAULT ASSUMPTIONS — matches the final v3 spec / the Excel reference file
   --------------------------------------------------------------------------- */
/* === DEFAULTS:START — regenerated by the in-page "Save as Default" admin
   tool every time it's used. Hand edits here are fine, but will be
   overwritten the next time someone saves new defaults from the page. === */
const DEFAULTS = {
  "volume": {
    "baseVolume": 30,
    "quarterlyGrowth": 0.3,
    "capacityPerDayPerTeam": 7,
    "teams": 1,
    "monthActive": [
      false,
      true,
      true,
      true,
      true,
      false,
      true,
      true,
      true,
      true,
      true,
      true
    ]
  },
  "revenue": {
    "examFeePrimary": 20,
    "pCompanion": 0.2,
    "examFeeCompanion": 12,
    "cvr": 0.85,
    "mix": [
      {
        "label": "Standard frame glasses + Atropine",
        "share": 0.3,
        "price": 52
      },
      {
        "label": "Myopia-control frame glasses — $120 tier (~VND 3M)",
        "share": 0.49,
        "price": 120
      },
      {
        "label": "Myopia-control frame glasses — $280 tier (~VND 7M)",
        "share": 0.21,
        "price": 280
      }
    ]
  },
  "costRates": {
    "outreachByQuarter": [
      0.6,
      0.5333,
      0.4667,
      0.4
    ],
    "logisticsPerVisit": 4,
    "cogsPct": 0.45
  },
  "fixedOverhead": [
    {
      "label": "Warehouse/office",
      "amount": 1000
    },
    {
      "label": "Utilities/Internet",
      "amount": 500
    }
  ],
  "headcount": [
    {
      "role": "Ophthalmologist (home visits)",
      "count": 1,
      "rate": 1000
    },
    {
      "role": "Refraction technician (accompanying)",
      "count": 1,
      "rate": 600
    },
    {
      "role": "Customer Care / Ops / Scheduling",
      "count": 1,
      "rate": 600
    }
  ],
  "scenario": {
    "conservativeAdj": -0.3,
    "optimisticAdj": 0.3
  },
  "capital": {
    "totalInvestment": 200000,
    "capexItems": [
      {
        "label": "Equipment (2 exam kits + computers/phones)",
        "amount": 50000,
        "month": 1
      },
      {
        "label": "Booking software/app — phase 1",
        "amount": 15000,
        "month": 1
      },
      {
        "label": "Booking software/app — phase 2",
        "amount": 15000,
        "month": 6
      }
    ]
  }
};
/* === DEFAULTS:END === */

/* Deep clone helper (structuredClone doesn't need a polyfill on modern browsers,
   but to stay safe on GitHub Pages / older browsers, use a hand-rolled JSON clone) */
function deepClone(obj) {
  return JSON.parse(JSON.stringify(obj));
}

let state = deepClone(DEFAULTS);
let currentScenario = "base"; // 'conservative' | 'base' | 'optimistic'

/* ---------------------------------------------------------------------------
   2. CALCULATION ENGINE — matches section 3 of the spec
   --------------------------------------------------------------------------- */
function computeRevenuePerVisit(s) {
  const expectedChildrenPerVisit = 1 + s.revenue.pCompanion;
  const examRevenuePerVisit = s.revenue.examFeePrimary + s.revenue.pCompanion * s.revenue.examFeeCompanion;
  const mixShareTotal = s.revenue.mix.reduce((sum, r) => sum + Number(r.share || 0), 0);
  const avgTreatmentValue = s.revenue.mix.reduce((sum, r) => sum + Number(r.share || 0) * Number(r.price || 0), 0);
  const treatmentRevenuePerVisit = expectedChildrenPerVisit * s.revenue.cvr * avgTreatmentValue;
  const totalRevenuePerVisit = examRevenuePerVisit + treatmentRevenuePerVisit;
  return {
    expectedChildrenPerVisit,
    examRevenuePerVisit,
    avgTreatmentValue,
    treatmentRevenuePerVisit,
    totalRevenuePerVisit,
    mixShareTotal
  };
}

function scenarioAdjustment(s, scenarioKey) {
  if (scenarioKey === "conservative") return s.scenario.conservativeAdj;
  if (scenarioKey === "optimistic") return s.scenario.optimisticAdj;
  return 0;
}

function calcModel(s, scenarioKey) {
  const rev = computeRevenuePerVisit(s);
  const adj = scenarioAdjustment(s, scenarioKey);
  const fixedOverheadMonthly = s.fixedOverhead.reduce((sum, r) => sum + Number(r.amount || 0), 0);
  const staffCostMonthly = s.headcount.reduce((sum, r) => sum + Number(r.count || 0) * Number(r.rate || 0), 0);

  const months = [];
  let cashBalance = 0;

  for (let m = 1; m <= 12; m++) {
    const q = Math.ceil(m / 3);
    const active = s.volume.monthActive && s.volume.monthActive[m - 1] !== undefined ? !!s.volume.monthActive[m - 1] : true;
    const volume = active ? (Number(s.volume.baseVolume || 0) * Math.pow(1 + Number(s.volume.quarterlyGrowth || 0), q - 1) * (1 + adj)) : 0;

    const monthlyRevenue = volume * rev.totalRevenuePerVisit;
    const examRevenue = volume * rev.examRevenuePerVisit;
    const treatmentRevenue = volume * rev.treatmentRevenuePerVisit;
    const cogs = treatmentRevenue * Number(s.costRates.cogsPct || 0);
    const outreachPct = Number(s.costRates.outreachByQuarter[q - 1] || 0);
    const marketing = monthlyRevenue * outreachPct;
    const logistics = volume * Number(s.costRates.logisticsPerVisit || 0);

    const variableCost = cogs + marketing + logistics;
    const grossProfit = monthlyRevenue - variableCost;

    const ebitda = grossProfit - fixedOverheadMonthly - staffCostMonthly;

    const capex = s.capital.capexItems.reduce((sum, item) => sum + (Number(item.month) === m ? Number(item.amount || 0) : 0), 0);
    const netCashFlow = ebitda - capex;

    cashBalance = (m === 1 ? Number(s.capital.totalInvestment || 0) : cashBalance) + netCashFlow;

    months.push({
      m, q, active, volume, monthlyRevenue, examRevenue, treatmentRevenue, cogs, outreachPct, marketing, logistics,
      variableCost, grossProfit, fixedOverheadMonthly, staffCostMonthly, ebitda, capex, netCashFlow, cashBalance
    });
  }

  const annual = months.reduce((acc, mo) => {
    acc.volume += mo.volume;
    acc.monthlyRevenue += mo.monthlyRevenue;
    acc.examRevenue += mo.examRevenue;
    acc.treatmentRevenue += mo.treatmentRevenue;
    acc.cogs += mo.cogs;
    acc.marketing += mo.marketing;
    acc.logistics += mo.logistics;
    acc.variableCost += mo.variableCost;
    acc.grossProfit += mo.grossProfit;
    acc.fixedOverheadMonthly += mo.fixedOverheadMonthly;
    acc.staffCostMonthly += mo.staffCostMonthly;
    acc.ebitda += mo.ebitda;
    acc.capex += mo.capex;
    acc.netCashFlow += mo.netCashFlow;
    return acc;
  }, { volume: 0, monthlyRevenue: 0, examRevenue: 0, treatmentRevenue: 0, cogs: 0, marketing: 0, logistics: 0, variableCost: 0, grossProfit: 0, fixedOverheadMonthly: 0, staffCostMonthly: 0, ebitda: 0, capex: 0, netCashFlow: 0 });

  annual.endingCash = months[11].cashBalance;
  annual.ebitdaMargin = annual.monthlyRevenue !== 0 ? annual.ebitda / annual.monthlyRevenue : 0;

  return { rev, months, annual };
}

/* Expose for console debugging / cross-check if needed */
window.__godsEyesB2C = { DEFAULTS, calcModel, computeRevenuePerVisit };
