/* ============================================================================
   God's Eyes · Financial Model — B2C Homecare (Children)
   The full calculation engine + rendering + interaction lives in this one file.
   Every input on the page is freely editable — no input is locked or
   auto-derived from another input.
   ============================================================================ */

/* ---------------------------------------------------------------------------
   0. ADMIN CONFIG — for the "Save as Default" tool in the Admin section.
   The PIN is a soft deterrent only (this is a static site — anyone can read
   this file), NOT real security. Change it before you deploy if you want a
   different one. It does not gate anything except showing the Admin form.
   --------------------------------------------------------------------------- */
const ADMIN_CONFIG = {
  pin: "2468"
};

/* ---------------------------------------------------------------------------
   1. DEFAULT ASSUMPTIONS — matches the final v3 spec / the Excel reference file
   --------------------------------------------------------------------------- */
/* === DEFAULTS:START — regenerated by the in-page "Save as Default" admin
   tool every time it's used. Hand edits here are fine, but will be
   overwritten the next time someone saves new defaults from the page. === */
const DEFAULTS = {
  volume: {
    baseVolume: 10,          // month 1-3 visits (Q1 rate) — FREE INPUT, see UI note
    quarterlyGrowth: 0.5,    // step-wise quarterly growth
    capacityPerDayPerTeam: 7, // reference only, NOT used in the formulas
    teams: 1,
    // Which of the 12 months the team is actually operating. Unchecking a
    // month (e.g. Tet/a holiday closure, or a ramp-up month with no revenue
    // yet) sets that month's visits to 0. Fixed overhead and staff cost still
    // apply (salaried staff are still paid). Default: M1 (too early to have
    // revenue yet) and M6 are closed.
    monthActive: [false, true, true, true, true, false, true, true, true, true, true, true]
  },
  revenue: {
    examFeePrimary: 30,
    pCompanion: 0.3,
    examFeeCompanion: 15,
    cvr: 0.85,
    mix: [
      { label: "Standard frame glasses + Atropine", share: 0.285, price: 52 },
      { label: "Myopia-control frame glasses — $120 tier (~VND 3M)", share: 0.475, price: 120 },
      { label: "Myopia-control frame glasses — $280 tier (~VND 7M)", share: 0.19, price: 280 },
      { label: "Ortho-K - $700 (~VND 18M)", share: 0.05, price: 700 }
    ]
  },
  // Fixed $ schedule, one editable field per month — NOT a % of revenue,
  // and NOT zeroed out by Active Months (branding/market-education spend
  // keeps running even during a closed/holiday month). Default: $10k/mo
  // for the first 3 months (branding push), $5k/mo from month 4 on —
  // every month is its own free input, this is just the starting point.
  marketing: {
    monthlyBudget: [10000, 10000, 10000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000, 5000]
  },
  costRates: {
    logisticsPerVisit: 2,
    cogsPct: 0.45
  },
  fixedOverhead: [
    { label: "Software maintenance/subscription", amount: 500 }
  ],
  // Each role is EITHER a fixed monthly salary (basis:"month", uses
  // monthlyRate) OR a per-exam stipend (basis:"exam", uses examRate) —
  // "per exam" means per CHILD examined, not per household visit: a visit
  // with a companion counts as 2 exams (see calcModel, multiplied by
  // rev.expectedChildrenPerVisit). Both rate fields are kept on every row
  // (not just the active one) so switching the toggle in the UI doesn't
  // lose whatever was typed into the other field. Doctor + Optometrist are
  // already salaried elsewhere (shared with Alina) so this project only
  // pays them a per-exam stipend; Ops/Customer Care is a dedicated hire,
  // still a fixed salary.
  headcount: [
    { role: "Doctor", count: 1, basis: "exam", monthlyRate: 0, examRate: 3.5 },
    { role: "Optometrist", count: 1, basis: "exam", monthlyRate: 0, examRate: 2 },
    { role: "Customer Care / Ops / Scheduling", count: 1, basis: "month", monthlyRate: 600, examRate: 0 }
  ],
  scenario: {
    conservativeAdj: -0.30,
    optimisticAdj: 0.30
  },
  capital: {
    totalInvestment: 150000,
    capexItems: [
      { label: "Equipment (2 exam kits)", amount: 40000, month: 1 },
      { label: "Booking software/app — phase 1", amount: 15000, month: 1 },
      { label: "Booking software/app — phase 2", amount: 15000, month: 6 }
    ]
  }
};
/* === DEFAULTS:END === */

/* Deep clone helper (structuredClone doesn't need a polyfill on modern browsers,
   but to stay safe on GitHub Pages / older browsers, use a hand-rolled JSON clone) */
function deepClone(obj) {
  return JSON.parse(JSON.stringify(obj));
}

let state = deepClone(DEFAULTS);
let currentScenario = "base"; // 'conservative' | 'base' | 'optimistic'

/* ---------------------------------------------------------------------------
   2. CALCULATION ENGINE — matches section 3 of the spec
   --------------------------------------------------------------------------- */
function computeRevenuePerVisit(s) {
  const expectedChildrenPerVisit = 1 + s.revenue.pCompanion;
  const examRevenuePerVisit = s.revenue.examFeePrimary + s.revenue.pCompanion * s.revenue.examFeeCompanion;
  const mixShareTotal = s.revenue.mix.reduce((sum, r) => sum + Number(r.share || 0), 0);
  const avgTreatmentValue = s.revenue.mix.reduce((sum, r) => sum + Number(r.share || 0) * Number(r.price || 0), 0);
  const treatmentRevenuePerVisit = expectedChildrenPerVisit * s.revenue.cvr * avgTreatmentValue;
  const totalRevenuePerVisit = examRevenuePerVisit + treatmentRevenuePerVisit;
  return {
    expectedChildrenPerVisit,
    examRevenuePerVisit,
    avgTreatmentValue,
    treatmentRevenuePerVisit,
    totalRevenuePerVisit,
    mixShareTotal
  };
}

function scenarioAdjustment(s, scenarioKey) {
  if (scenarioKey === "conservative") return s.scenario.conservativeAdj;
  if (scenarioKey === "optimistic") return s.scenario.optimisticAdj;
  return 0;
}

function calcModel(s, scenarioKey) {
  const rev = computeRevenuePerVisit(s);
  const adj = scenarioAdjustment(s, scenarioKey);
  const fixedOverheadMonthly = s.fixedOverhead.reduce((sum, r) => sum + Number(r.amount || 0), 0);

  const months = [];
  let cashBalance = 0;

  for (let m = 1; m <= 12; m++) {
    const q = Math.ceil(m / 3);
    const active = s.volume.monthActive && s.volume.monthActive[m - 1] !== undefined ? !!s.volume.monthActive[m - 1] : true;
    const volume = active ? (Number(s.volume.baseVolume || 0) * Math.pow(1 + Number(s.volume.quarterlyGrowth || 0), q - 1) * (1 + adj)) : 0;

    const monthlyRevenue = volume * rev.totalRevenuePerVisit;
    const examRevenue = volume * rev.examRevenuePerVisit;
    const treatmentRevenue = volume * rev.treatmentRevenuePerVisit;
    const cogs = treatmentRevenue * Number(s.costRates.cogsPct || 0);
    // Fixed $ schedule, one free input per month — independent of revenue
    // AND independent of `active` (keeps running through closed months).
    const marketing = Number(s.marketing.monthlyBudget[m - 1] || 0);
    const logistics = volume * Number(s.costRates.logisticsPerVisit || 0);

    const variableCost = cogs + marketing + logistics;
    const grossProfit = monthlyRevenue - variableCost;

    // Staff cost now depends on `volume`, so it's computed per-month rather
    // than once outside the loop: "month" basis roles are a flat salary
    // regardless of volume. "exam" basis roles are paid per CHILD examined,
    // not per household visit — a visit with a companion is 2 exams, so the
    // per-visit volume is scaled up by rev.expectedChildrenPerVisit (the
    // same expected-value factor already used for treatment revenue).
    const staffCostMonthly = s.headcount.reduce((sum, r) => {
      const isExam = r.basis === "exam";
      const rate = isExam ? Number(r.examRate || 0) : Number(r.monthlyRate || 0);
      const amt = Number(r.count || 0) * rate;
      return sum + (isExam ? amt * volume * rev.expectedChildrenPerVisit : amt);
    }, 0);

    const ebitda = grossProfit - fixedOverheadMonthly - staffCostMonthly;

    const capex = s.capital.capexItems.reduce((sum, item) => sum + (Number(item.month) === m ? Number(item.amount || 0) : 0), 0);
    const netCashFlow = ebitda - capex;

    cashBalance = (m === 1 ? Number(s.capital.totalInvestment || 0) : cashBalance) + netCashFlow;

    months.push({
      m, q, active, volume, monthlyRevenue, examRevenue, treatmentRevenue, cogs, marketing, logistics,
      variableCost, grossProfit, fixedOverheadMonthly, staffCostMonthly, ebitda, capex, netCashFlow, cashBalance
    });
  }

  const annual = months.reduce((acc, mo) => {
    acc.volume += mo.volume;
    acc.monthlyRevenue += mo.monthlyRevenue;
    acc.examRevenue += mo.examRevenue;
    acc.treatmentRevenue += mo.treatmentRevenue;
    acc.cogs += mo.cogs;
    acc.marketing += mo.marketing;
    acc.logistics += mo.logistics;
    acc.variableCost += mo.variableCost;
    acc.grossProfit += mo.grossProfit;
    acc.fixedOverheadMonthly += mo.fixedOverheadMonthly;
    acc.staffCostMonthly += mo.staffCostMonthly;
    acc.ebitda += mo.ebitda;
    acc.capex += mo.capex;
    acc.netCashFlow += mo.netCashFlow;
    return acc;
  }, { volume: 0, monthlyRevenue: 0, examRevenue: 0, treatmentRevenue: 0, cogs: 0, marketing: 0, logistics: 0, variableCost: 0, grossProfit: 0, fixedOverheadMonthly: 0, staffCostMonthly: 0, ebitda: 0, capex: 0, netCashFlow: 0 });

  annual.endingCash = months[11].cashBalance;
  annual.ebitdaMargin = annual.monthlyRevenue !== 0 ? annual.ebitda / annual.monthlyRevenue : 0;

  return { rev, months, annual };
}

/* Expose for console debugging / cross-check if needed */
window.__godsEyesB2C = { DEFAULTS, calcModel, computeRevenuePerVisit };
